version: '3.7'

services:
  # Backend service
  backend:
    image: php:8.2-fpm
    container_name: laravel-backend
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./src:/var/www
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=ecommerce
      - DB_USERNAME=app_user
      - DB_PASSWORD=a

  # Web server (Nginx)
  webserver:
    image: nginx:1.26.2-alpine
    container_name: nginx-webserver
    volumes:
      - ./src/public:/var/www/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - backend

  # Database service
  db:
    image: mysql:8.0
    container_name: ecommerce-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: app_user
      MYSQL_PASSWORD: a
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
